//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfacesMatasanos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class UsuarioEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FDUIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FDUI {
            get {
                return this.FDUIField;
            }
            set {
                if ((object.ReferenceEquals(this.FDUIField, value) != true)) {
                    this.FDUIField = value;
                    this.RaisePropertyChanged("FDUI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicoEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class MedicoEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkPlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkPlanta {
            get {
                return this.FkPlantaField;
            }
            set {
                if ((this.FkPlantaField.Equals(value) != true)) {
                    this.FkPlantaField = value;
                    this.RaisePropertyChanged("FkPlanta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdMedico {
            get {
                return this.IdMedicoField;
            }
            set {
                if ((this.IdMedicoField.Equals(value) != true)) {
                    this.IdMedicoField = value;
                    this.RaisePropertyChanged("IdMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnfermeraEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class EnfermeraEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DUIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DUI {
            get {
                return this.DUIField;
            }
            set {
                if ((object.ReferenceEquals(this.DUIField, value) != true)) {
                    this.DUIField = value;
                    this.RaisePropertyChanged("DUI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class HistorialEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkNumeroSeguroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdHistorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoP {
            get {
                return this.ApellidoPField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPField, value) != true)) {
                    this.ApellidoPField = value;
                    this.RaisePropertyChanged("ApellidoP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniP {
            get {
                return this.DniPField;
            }
            set {
                if ((object.ReferenceEquals(this.DniPField, value) != true)) {
                    this.DniPField = value;
                    this.RaisePropertyChanged("DniP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaAltaField, value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEntrada {
            get {
                return this.FechaEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEntradaField, value) != true)) {
                    this.FechaEntradaField = value;
                    this.RaisePropertyChanged("FechaEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkNumeroSeguro {
            get {
                return this.FkNumeroSeguroField;
            }
            set {
                if ((this.FkNumeroSeguroField.Equals(value) != true)) {
                    this.FkNumeroSeguroField = value;
                    this.RaisePropertyChanged("FkNumeroSeguro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdHistorial {
            get {
                return this.IdHistorialField;
            }
            set {
                if ((this.IdHistorialField.Equals(value) != true)) {
                    this.IdHistorialField = value;
                    this.RaisePropertyChanged("IdHistorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreP {
            get {
                return this.NombrePField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePField, value) != true)) {
                    this.NombrePField = value;
                    this.RaisePropertyChanged("NombreP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CamaEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class CamaEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkPlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdCamaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkPlanta {
            get {
                return this.FkPlantaField;
            }
            set {
                if ((this.FkPlantaField.Equals(value) != true)) {
                    this.FkPlantaField = value;
                    this.RaisePropertyChanged("FkPlanta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdCama {
            get {
                return this.IdCamaField;
            }
            set {
                if ((this.IdCamaField.Equals(value) != true)) {
                    this.IdCamaField = value;
                    this.RaisePropertyChanged("IdCama");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class PacienteEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdNumeroSeguroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNacimientoField, value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdNumeroSeguro {
            get {
                return this.IdNumeroSeguroField;
            }
            set {
                if ((this.IdNumeroSeguroField.Equals(value) != true)) {
                    this.IdNumeroSeguroField = value;
                    this.RaisePropertyChanged("IdNumeroSeguro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteCamaEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class PacienteCamaEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaAsignadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkCamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkHistoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdPacienteCamaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaAsignada {
            get {
                return this.FechaAsignadaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaAsignadaField, value) != true)) {
                    this.FechaAsignadaField = value;
                    this.RaisePropertyChanged("FechaAsignada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkCama {
            get {
                return this.FkCamaField;
            }
            set {
                if ((this.FkCamaField.Equals(value) != true)) {
                    this.FkCamaField = value;
                    this.RaisePropertyChanged("FkCama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkHistoria {
            get {
                return this.FkHistoriaField;
            }
            set {
                if ((this.FkHistoriaField.Equals(value) != true)) {
                    this.FkHistoriaField = value;
                    this.RaisePropertyChanged("FkHistoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdPacienteCama {
            get {
                return this.IdPacienteCamaField;
            }
            set {
                if ((this.IdPacienteCamaField.Equals(value) != true)) {
                    this.IdPacienteCamaField = value;
                    this.RaisePropertyChanged("IdPacienteCama");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisitaMedicaEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class VisitaMedicaEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaignosticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVisitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FkPacienteCamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraVisitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Daignostico {
            get {
                return this.DaignosticoField;
            }
            set {
                if ((object.ReferenceEquals(this.DaignosticoField, value) != true)) {
                    this.DaignosticoField = value;
                    this.RaisePropertyChanged("Daignostico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVisita {
            get {
                return this.FechaVisitaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVisitaField, value) != true)) {
                    this.FechaVisitaField = value;
                    this.RaisePropertyChanged("FechaVisita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkMedico {
            get {
                return this.FkMedicoField;
            }
            set {
                if ((this.FkMedicoField.Equals(value) != true)) {
                    this.FkMedicoField = value;
                    this.RaisePropertyChanged("FkMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FkPacienteCama {
            get {
                return this.FkPacienteCamaField;
            }
            set {
                if ((this.FkPacienteCamaField.Equals(value) != true)) {
                    this.FkPacienteCamaField = value;
                    this.RaisePropertyChanged("FkPacienteCama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraVisita {
            get {
                return this.HoraVisitaField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraVisitaField, value) != true)) {
                    this.HoraVisitaField = value;
                    this.RaisePropertyChanged("HoraVisita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlantaEN", Namespace="http://schemas.datacontract.org/2004/07/EN")]
    [System.SerializableAttribute()]
    public partial class PlantaEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdPlantaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCamasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdPlanta {
            get {
                return this.IdPlantaField;
            }
            set {
                if ((this.IdPlantaField.Equals(value) != true)) {
                    this.IdPlantaField = value;
                    this.RaisePropertyChanged("IdPlanta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCamas {
            get {
                return this.NumeroCamasField;
            }
            set {
                if ((this.NumeroCamasField.Equals(value) != true)) {
                    this.NumeroCamasField = value;
                    this.RaisePropertyChanged("NumeroCamas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IniciarSesion", ReplyAction="http://tempuri.org/IService1/IniciarSesionResponse")]
        int IniciarSesion(InterfacesMatasanos.ServiceReference1.UsuarioEN pValidar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IniciarSesion", ReplyAction="http://tempuri.org/IService1/IniciarSesionResponse")]
        System.Threading.Tasks.Task<int> IniciarSesionAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pValidar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarUsuario", ReplyAction="http://tempuri.org/IService1/RegistrarUsuarioResponse")]
        string RegistrarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarUsuario", ReplyAction="http://tempuri.org/IService1/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarUsuario", ReplyAction="http://tempuri.org/IService1/ModificarUsuarioResponse")]
        string ModificarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarUsuario", ReplyAction="http://tempuri.org/IService1/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<string> ModificarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarUsuario", ReplyAction="http://tempuri.org/IService1/EliminarUsuarioResponse")]
        int EliminarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarUsuario", ReplyAction="http://tempuri.org/IService1/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<int> EliminarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarUsuarios", ReplyAction="http://tempuri.org/IService1/MostrarUsuariosResponse")]
        InterfacesMatasanos.ServiceReference1.UsuarioEN[] MostrarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarUsuarios", ReplyAction="http://tempuri.org/IService1/MostrarUsuariosResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.UsuarioEN[]> MostrarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        InterfacesMatasanos.ServiceReference1.UsuarioEN[] BuscarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.UsuarioEN[]> BuscarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validar", ReplyAction="http://tempuri.org/IService1/ValidarResponse")]
        int Validar(InterfacesMatasanos.ServiceReference1.MedicoEN pValidar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validar", ReplyAction="http://tempuri.org/IService1/ValidarResponse")]
        System.Threading.Tasks.Task<int> ValidarAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pValidar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarMedico", ReplyAction="http://tempuri.org/IService1/AgregarMedicoResponse")]
        string AgregarMedico(InterfacesMatasanos.ServiceReference1.MedicoEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarMedico", ReplyAction="http://tempuri.org/IService1/AgregarMedicoResponse")]
        System.Threading.Tasks.Task<string> AgregarMedicoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarMedico", ReplyAction="http://tempuri.org/IService1/ActualizarMedicoResponse")]
        int ActualizarMedico(InterfacesMatasanos.ServiceReference1.MedicoEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarMedico", ReplyAction="http://tempuri.org/IService1/ActualizarMedicoResponse")]
        System.Threading.Tasks.Task<int> ActualizarMedicoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarMedico", ReplyAction="http://tempuri.org/IService1/EliminarMedicoResponse")]
        int EliminarMedico(InterfacesMatasanos.ServiceReference1.MedicoEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarMedico", ReplyAction="http://tempuri.org/IService1/EliminarMedicoResponse")]
        System.Threading.Tasks.Task<int> EliminarMedicoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarMedico", ReplyAction="http://tempuri.org/IService1/MostrarMedicoResponse")]
        InterfacesMatasanos.ServiceReference1.MedicoEN[] MostrarMedico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarMedico", ReplyAction="http://tempuri.org/IService1/MostrarMedicoResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> MostrarMedicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarMedicoApellido", ReplyAction="http://tempuri.org/IService1/BuscarMedicoApellidoResponse")]
        InterfacesMatasanos.ServiceReference1.MedicoEN[] BuscarMedicoApellido(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarMedicoApellido", ReplyAction="http://tempuri.org/IService1/BuscarMedicoApellidoResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> BuscarMedicoApellidoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarMedicoEspecialidad", ReplyAction="http://tempuri.org/IService1/BuscarMedicoEspecialidadResponse")]
        InterfacesMatasanos.ServiceReference1.MedicoEN[] BuscarMedicoEspecialidad(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarMedicoEspecialidad", ReplyAction="http://tempuri.org/IService1/BuscarMedicoEspecialidadResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> BuscarMedicoEspecialidadAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerImagen", ReplyAction="http://tempuri.org/IService1/ObtenerImagenResponse")]
        InterfacesMatasanos.ServiceReference1.MedicoEN[] ObtenerImagen(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerImagen", ReplyAction="http://tempuri.org/IService1/ObtenerImagenResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> ObtenerImagenAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReguistraEnfermero", ReplyAction="http://tempuri.org/IService1/ReguistraEnfermeroResponse")]
        string ReguistraEnfermero(InterfacesMatasanos.ServiceReference1.EnfermeraEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReguistraEnfermero", ReplyAction="http://tempuri.org/IService1/ReguistraEnfermeroResponse")]
        System.Threading.Tasks.Task<string> ReguistraEnfermeroAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarEnfermeras", ReplyAction="http://tempuri.org/IService1/EliminarEnfermerasResponse")]
        int EliminarEnfermeras(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarEnfermeras", ReplyAction="http://tempuri.org/IService1/EliminarEnfermerasResponse")]
        System.Threading.Tasks.Task<int> EliminarEnfermerasAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarEnfermeras", ReplyAction="http://tempuri.org/IService1/ModificarEnfermerasResponse")]
        int ModificarEnfermeras(InterfacesMatasanos.ServiceReference1.EnfermeraEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarEnfermeras", ReplyAction="http://tempuri.org/IService1/ModificarEnfermerasResponse")]
        System.Threading.Tasks.Task<int> ModificarEnfermerasAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarEnfermeras", ReplyAction="http://tempuri.org/IService1/MostrarEnfermerasResponse")]
        InterfacesMatasanos.ServiceReference1.EnfermeraEN[] MostrarEnfermeras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarEnfermeras", ReplyAction="http://tempuri.org/IService1/MostrarEnfermerasResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.EnfermeraEN[]> MostrarEnfermerasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarEnfermera", ReplyAction="http://tempuri.org/IService1/BuscarEnfermeraResponse")]
        InterfacesMatasanos.ServiceReference1.EnfermeraEN[] BuscarEnfermera(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEnfermera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarEnfermera", ReplyAction="http://tempuri.org/IService1/BuscarEnfermeraResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.EnfermeraEN[]> BuscarEnfermeraAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEnfermera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarHistorial", ReplyAction="http://tempuri.org/IService1/ModificarHistorialResponse")]
        int ModificarHistorial(InterfacesMatasanos.ServiceReference1.HistorialEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarHistorial", ReplyAction="http://tempuri.org/IService1/ModificarHistorialResponse")]
        System.Threading.Tasks.Task<int> ModificarHistorialAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarHistorial", ReplyAction="http://tempuri.org/IService1/AgregarHistorialResponse")]
        int AgregarHistorial(InterfacesMatasanos.ServiceReference1.HistorialEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarHistorial", ReplyAction="http://tempuri.org/IService1/AgregarHistorialResponse")]
        System.Threading.Tasks.Task<int> AgregarHistorialAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarHistorial", ReplyAction="http://tempuri.org/IService1/MostrarHistorialResponse")]
        InterfacesMatasanos.ServiceReference1.HistorialEN[] MostrarHistorial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarHistorial", ReplyAction="http://tempuri.org/IService1/MostrarHistorialResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> MostrarHistorialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarHistorial", ReplyAction="http://tempuri.org/IService1/BuscarHistorialResponse")]
        InterfacesMatasanos.ServiceReference1.HistorialEN[] BuscarHistorial(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarHistorial", ReplyAction="http://tempuri.org/IService1/BuscarHistorialResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> BuscarHistorialAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarHistorialPorFechaEntrada", ReplyAction="http://tempuri.org/IService1/BuscarHistorialPorFechaEntradaResponse")]
        InterfacesMatasanos.ServiceReference1.HistorialEN[] BuscarHistorialPorFechaEntrada(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarHistorialPorFechaEntrada", ReplyAction="http://tempuri.org/IService1/BuscarHistorialPorFechaEntradaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> BuscarHistorialPorFechaEntradaAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarHistorialPorFechaAlta", ReplyAction="http://tempuri.org/IService1/BuscarHistorialPorFechaAltaResponse")]
        InterfacesMatasanos.ServiceReference1.HistorialEN[] BuscarHistorialPorFechaAlta(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarHistorialPorFechaAlta", ReplyAction="http://tempuri.org/IService1/BuscarHistorialPorFechaAltaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> BuscarHistorialPorFechaAltaAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCama", ReplyAction="http://tempuri.org/IService1/AgregarCamaResponse")]
        int AgregarCama(InterfacesMatasanos.ServiceReference1.CamaEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCama", ReplyAction="http://tempuri.org/IService1/AgregarCamaResponse")]
        System.Threading.Tasks.Task<int> AgregarCamaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarCama", ReplyAction="http://tempuri.org/IService1/ModificarCamaResponse")]
        int ModificarCama(InterfacesMatasanos.ServiceReference1.CamaEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarCama", ReplyAction="http://tempuri.org/IService1/ModificarCamaResponse")]
        System.Threading.Tasks.Task<int> ModificarCamaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCama", ReplyAction="http://tempuri.org/IService1/EliminarCamaResponse")]
        int EliminarCama(InterfacesMatasanos.ServiceReference1.CamaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCama", ReplyAction="http://tempuri.org/IService1/EliminarCamaResponse")]
        System.Threading.Tasks.Task<int> EliminarCamaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarCama", ReplyAction="http://tempuri.org/IService1/MostrarCamaResponse")]
        InterfacesMatasanos.ServiceReference1.CamaEN[] MostrarCama();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarCama", ReplyAction="http://tempuri.org/IService1/MostrarCamaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.CamaEN[]> MostrarCamaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarCamaPlanta", ReplyAction="http://tempuri.org/IService1/BuscarCamaPlantaResponse")]
        InterfacesMatasanos.ServiceReference1.CamaEN[] BuscarCamaPlanta(InterfacesMatasanos.ServiceReference1.CamaEN pCama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarCamaPlanta", ReplyAction="http://tempuri.org/IService1/BuscarCamaPlantaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.CamaEN[]> BuscarCamaPlantaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pCama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarPaciente", ReplyAction="http://tempuri.org/IService1/AgregarPacienteResponse")]
        string AgregarPaciente(InterfacesMatasanos.ServiceReference1.PacienteEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarPaciente", ReplyAction="http://tempuri.org/IService1/AgregarPacienteResponse")]
        System.Threading.Tasks.Task<string> AgregarPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPaciente", ReplyAction="http://tempuri.org/IService1/ActualizarPacienteResponse")]
        int ActualizarPaciente(InterfacesMatasanos.ServiceReference1.PacienteEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPaciente", ReplyAction="http://tempuri.org/IService1/ActualizarPacienteResponse")]
        System.Threading.Tasks.Task<int> ActualizarPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarPaciente", ReplyAction="http://tempuri.org/IService1/MostrarPacienteResponse")]
        InterfacesMatasanos.ServiceReference1.PacienteEN[] MostrarPaciente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarPaciente", ReplyAction="http://tempuri.org/IService1/MostrarPacienteResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteEN[]> MostrarPacienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPacientePordni", ReplyAction="http://tempuri.org/IService1/BuscarPacientePordniResponse")]
        InterfacesMatasanos.ServiceReference1.PacienteEN[] BuscarPacientePordni(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPacientePordni", ReplyAction="http://tempuri.org/IService1/BuscarPacientePordniResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteEN[]> BuscarPacientePordniAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPacientePorEstado", ReplyAction="http://tempuri.org/IService1/BuscarPacientePorEstadoResponse")]
        InterfacesMatasanos.ServiceReference1.PacienteEN[] BuscarPacientePorEstado(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPacientePorEstado", ReplyAction="http://tempuri.org/IService1/BuscarPacientePorEstadoResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteEN[]> BuscarPacientePorEstadoAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCamaAPaciente", ReplyAction="http://tempuri.org/IService1/AgregarCamaAPacienteResponse")]
        int AgregarCamaAPaciente(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCamaAPaciente", ReplyAction="http://tempuri.org/IService1/AgregarCamaAPacienteResponse")]
        System.Threading.Tasks.Task<int> AgregarCamaAPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCamaAPaciente", ReplyAction="http://tempuri.org/IService1/ActualizarCamaAPacienteResponse")]
        int ActualizarCamaAPaciente(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCamaAPaciente", ReplyAction="http://tempuri.org/IService1/ActualizarCamaAPacienteResponse")]
        System.Threading.Tasks.Task<int> ActualizarCamaAPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCamaAPaciente", ReplyAction="http://tempuri.org/IService1/EliminarCamaAPacienteResponse")]
        int EliminarCamaAPaciente(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCamaAPaciente", ReplyAction="http://tempuri.org/IService1/EliminarCamaAPacienteResponse")]
        System.Threading.Tasks.Task<int> EliminarCamaAPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarPacienteCama", ReplyAction="http://tempuri.org/IService1/MostrarPacienteCamaResponse")]
        InterfacesMatasanos.ServiceReference1.PacienteCamaEN[] MostrarPacienteCama();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarPacienteCama", ReplyAction="http://tempuri.org/IService1/MostrarPacienteCamaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteCamaEN[]> MostrarPacienteCamaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscraCamaPacientePorFecha", ReplyAction="http://tempuri.org/IService1/BuscraCamaPacientePorFechaResponse")]
        InterfacesMatasanos.ServiceReference1.PacienteCamaEN[] BuscraCamaPacientePorFecha(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscraCamaPacientePorFecha", ReplyAction="http://tempuri.org/IService1/BuscraCamaPacientePorFechaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteCamaEN[]> BuscraCamaPacientePorFechaAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarVisita", ReplyAction="http://tempuri.org/IService1/AgregarVisitaResponse")]
        int AgregarVisita(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarVisita", ReplyAction="http://tempuri.org/IService1/AgregarVisitaResponse")]
        System.Threading.Tasks.Task<int> AgregarVisitaAsync(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarVisita", ReplyAction="http://tempuri.org/IService1/EliminarVisitaResponse")]
        int EliminarVisita(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarVisita", ReplyAction="http://tempuri.org/IService1/EliminarVisitaResponse")]
        System.Threading.Tasks.Task<int> EliminarVisitaAsync(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarVisita", ReplyAction="http://tempuri.org/IService1/MostrarVisitaResponse")]
        InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[] MostrarVisita();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarVisita", ReplyAction="http://tempuri.org/IService1/MostrarVisitaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[]> MostrarVisitaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarVisita", ReplyAction="http://tempuri.org/IService1/BuscarVisitaResponse")]
        InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[] BuscarVisita(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pVisita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarVisita", ReplyAction="http://tempuri.org/IService1/BuscarVisitaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[]> BuscarVisitaAsync(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pVisita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarPlanta", ReplyAction="http://tempuri.org/IService1/AgregarPlantaResponse")]
        string AgregarPlanta(InterfacesMatasanos.ServiceReference1.PlantaEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarPlanta", ReplyAction="http://tempuri.org/IService1/AgregarPlantaResponse")]
        System.Threading.Tasks.Task<string> AgregarPlantaAsync(InterfacesMatasanos.ServiceReference1.PlantaEN pAgregar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPlanta", ReplyAction="http://tempuri.org/IService1/ActualizarPlantaResponse")]
        int ActualizarPlanta(InterfacesMatasanos.ServiceReference1.PlantaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPlanta", ReplyAction="http://tempuri.org/IService1/ActualizarPlantaResponse")]
        System.Threading.Tasks.Task<int> ActualizarPlantaAsync(InterfacesMatasanos.ServiceReference1.PlantaEN pEliminar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostraPlantas", ReplyAction="http://tempuri.org/IService1/MostraPlantasResponse")]
        InterfacesMatasanos.ServiceReference1.PlantaEN[] MostraPlantas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostraPlantas", ReplyAction="http://tempuri.org/IService1/MostraPlantasResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PlantaEN[]> MostraPlantasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPlanta", ReplyAction="http://tempuri.org/IService1/BuscarPlantaResponse")]
        InterfacesMatasanos.ServiceReference1.PlantaEN[] BuscarPlanta(InterfacesMatasanos.ServiceReference1.PlantaEN pPlanta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPlanta", ReplyAction="http://tempuri.org/IService1/BuscarPlantaResponse")]
        System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PlantaEN[]> BuscarPlantaAsync(InterfacesMatasanos.ServiceReference1.PlantaEN pPlanta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : InterfacesMatasanos.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<InterfacesMatasanos.ServiceReference1.IService1>, InterfacesMatasanos.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int IniciarSesion(InterfacesMatasanos.ServiceReference1.UsuarioEN pValidar) {
            return base.Channel.IniciarSesion(pValidar);
        }
        
        public System.Threading.Tasks.Task<int> IniciarSesionAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pValidar) {
            return base.Channel.IniciarSesionAsync(pValidar);
        }
        
        public string RegistrarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pAgregar) {
            return base.Channel.RegistrarUsuario(pAgregar);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pAgregar) {
            return base.Channel.RegistrarUsuarioAsync(pAgregar);
        }
        
        public string ModificarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pModificar) {
            return base.Channel.ModificarUsuario(pModificar);
        }
        
        public System.Threading.Tasks.Task<string> ModificarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pModificar) {
            return base.Channel.ModificarUsuarioAsync(pModificar);
        }
        
        public int EliminarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pEliminar) {
            return base.Channel.EliminarUsuario(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> EliminarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pEliminar) {
            return base.Channel.EliminarUsuarioAsync(pEliminar);
        }
        
        public InterfacesMatasanos.ServiceReference1.UsuarioEN[] MostrarUsuarios() {
            return base.Channel.MostrarUsuarios();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.UsuarioEN[]> MostrarUsuariosAsync() {
            return base.Channel.MostrarUsuariosAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.UsuarioEN[] BuscarUsuario(InterfacesMatasanos.ServiceReference1.UsuarioEN pUsuario) {
            return base.Channel.BuscarUsuario(pUsuario);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.UsuarioEN[]> BuscarUsuarioAsync(InterfacesMatasanos.ServiceReference1.UsuarioEN pUsuario) {
            return base.Channel.BuscarUsuarioAsync(pUsuario);
        }
        
        public int Validar(InterfacesMatasanos.ServiceReference1.MedicoEN pValidar) {
            return base.Channel.Validar(pValidar);
        }
        
        public System.Threading.Tasks.Task<int> ValidarAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pValidar) {
            return base.Channel.ValidarAsync(pValidar);
        }
        
        public string AgregarMedico(InterfacesMatasanos.ServiceReference1.MedicoEN pAgregar) {
            return base.Channel.AgregarMedico(pAgregar);
        }
        
        public System.Threading.Tasks.Task<string> AgregarMedicoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pAgregar) {
            return base.Channel.AgregarMedicoAsync(pAgregar);
        }
        
        public int ActualizarMedico(InterfacesMatasanos.ServiceReference1.MedicoEN pModificar) {
            return base.Channel.ActualizarMedico(pModificar);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarMedicoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pModificar) {
            return base.Channel.ActualizarMedicoAsync(pModificar);
        }
        
        public int EliminarMedico(InterfacesMatasanos.ServiceReference1.MedicoEN pEliminar) {
            return base.Channel.EliminarMedico(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> EliminarMedicoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pEliminar) {
            return base.Channel.EliminarMedicoAsync(pEliminar);
        }
        
        public InterfacesMatasanos.ServiceReference1.MedicoEN[] MostrarMedico() {
            return base.Channel.MostrarMedico();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> MostrarMedicoAsync() {
            return base.Channel.MostrarMedicoAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.MedicoEN[] BuscarMedicoApellido(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN) {
            return base.Channel.BuscarMedicoApellido(pMedicoEN);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> BuscarMedicoApellidoAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN) {
            return base.Channel.BuscarMedicoApellidoAsync(pMedicoEN);
        }
        
        public InterfacesMatasanos.ServiceReference1.MedicoEN[] BuscarMedicoEspecialidad(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN) {
            return base.Channel.BuscarMedicoEspecialidad(pMedicoEN);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> BuscarMedicoEspecialidadAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN) {
            return base.Channel.BuscarMedicoEspecialidadAsync(pMedicoEN);
        }
        
        public InterfacesMatasanos.ServiceReference1.MedicoEN[] ObtenerImagen(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN) {
            return base.Channel.ObtenerImagen(pMedicoEN);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.MedicoEN[]> ObtenerImagenAsync(InterfacesMatasanos.ServiceReference1.MedicoEN pMedicoEN) {
            return base.Channel.ObtenerImagenAsync(pMedicoEN);
        }
        
        public string ReguistraEnfermero(InterfacesMatasanos.ServiceReference1.EnfermeraEN pAgregar) {
            return base.Channel.ReguistraEnfermero(pAgregar);
        }
        
        public System.Threading.Tasks.Task<string> ReguistraEnfermeroAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pAgregar) {
            return base.Channel.ReguistraEnfermeroAsync(pAgregar);
        }
        
        public int EliminarEnfermeras(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEliminar) {
            return base.Channel.EliminarEnfermeras(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> EliminarEnfermerasAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEliminar) {
            return base.Channel.EliminarEnfermerasAsync(pEliminar);
        }
        
        public int ModificarEnfermeras(InterfacesMatasanos.ServiceReference1.EnfermeraEN pModificar) {
            return base.Channel.ModificarEnfermeras(pModificar);
        }
        
        public System.Threading.Tasks.Task<int> ModificarEnfermerasAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pModificar) {
            return base.Channel.ModificarEnfermerasAsync(pModificar);
        }
        
        public InterfacesMatasanos.ServiceReference1.EnfermeraEN[] MostrarEnfermeras() {
            return base.Channel.MostrarEnfermeras();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.EnfermeraEN[]> MostrarEnfermerasAsync() {
            return base.Channel.MostrarEnfermerasAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.EnfermeraEN[] BuscarEnfermera(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEnfermera) {
            return base.Channel.BuscarEnfermera(pEnfermera);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.EnfermeraEN[]> BuscarEnfermeraAsync(InterfacesMatasanos.ServiceReference1.EnfermeraEN pEnfermera) {
            return base.Channel.BuscarEnfermeraAsync(pEnfermera);
        }
        
        public int ModificarHistorial(InterfacesMatasanos.ServiceReference1.HistorialEN pModificar) {
            return base.Channel.ModificarHistorial(pModificar);
        }
        
        public System.Threading.Tasks.Task<int> ModificarHistorialAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pModificar) {
            return base.Channel.ModificarHistorialAsync(pModificar);
        }
        
        public int AgregarHistorial(InterfacesMatasanos.ServiceReference1.HistorialEN pAgregar) {
            return base.Channel.AgregarHistorial(pAgregar);
        }
        
        public System.Threading.Tasks.Task<int> AgregarHistorialAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pAgregar) {
            return base.Channel.AgregarHistorialAsync(pAgregar);
        }
        
        public InterfacesMatasanos.ServiceReference1.HistorialEN[] MostrarHistorial() {
            return base.Channel.MostrarHistorial();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> MostrarHistorialAsync() {
            return base.Channel.MostrarHistorialAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.HistorialEN[] BuscarHistorial(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial) {
            return base.Channel.BuscarHistorial(pHistorial);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> BuscarHistorialAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial) {
            return base.Channel.BuscarHistorialAsync(pHistorial);
        }
        
        public InterfacesMatasanos.ServiceReference1.HistorialEN[] BuscarHistorialPorFechaEntrada(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial) {
            return base.Channel.BuscarHistorialPorFechaEntrada(pHistorial);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> BuscarHistorialPorFechaEntradaAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial) {
            return base.Channel.BuscarHistorialPorFechaEntradaAsync(pHistorial);
        }
        
        public InterfacesMatasanos.ServiceReference1.HistorialEN[] BuscarHistorialPorFechaAlta(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial) {
            return base.Channel.BuscarHistorialPorFechaAlta(pHistorial);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.HistorialEN[]> BuscarHistorialPorFechaAltaAsync(InterfacesMatasanos.ServiceReference1.HistorialEN pHistorial) {
            return base.Channel.BuscarHistorialPorFechaAltaAsync(pHistorial);
        }
        
        public int AgregarCama(InterfacesMatasanos.ServiceReference1.CamaEN pAgregar) {
            return base.Channel.AgregarCama(pAgregar);
        }
        
        public System.Threading.Tasks.Task<int> AgregarCamaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pAgregar) {
            return base.Channel.AgregarCamaAsync(pAgregar);
        }
        
        public int ModificarCama(InterfacesMatasanos.ServiceReference1.CamaEN pModificar) {
            return base.Channel.ModificarCama(pModificar);
        }
        
        public System.Threading.Tasks.Task<int> ModificarCamaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pModificar) {
            return base.Channel.ModificarCamaAsync(pModificar);
        }
        
        public int EliminarCama(InterfacesMatasanos.ServiceReference1.CamaEN pEliminar) {
            return base.Channel.EliminarCama(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> EliminarCamaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pEliminar) {
            return base.Channel.EliminarCamaAsync(pEliminar);
        }
        
        public InterfacesMatasanos.ServiceReference1.CamaEN[] MostrarCama() {
            return base.Channel.MostrarCama();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.CamaEN[]> MostrarCamaAsync() {
            return base.Channel.MostrarCamaAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.CamaEN[] BuscarCamaPlanta(InterfacesMatasanos.ServiceReference1.CamaEN pCama) {
            return base.Channel.BuscarCamaPlanta(pCama);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.CamaEN[]> BuscarCamaPlantaAsync(InterfacesMatasanos.ServiceReference1.CamaEN pCama) {
            return base.Channel.BuscarCamaPlantaAsync(pCama);
        }
        
        public string AgregarPaciente(InterfacesMatasanos.ServiceReference1.PacienteEN pAgregar) {
            return base.Channel.AgregarPaciente(pAgregar);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pAgregar) {
            return base.Channel.AgregarPacienteAsync(pAgregar);
        }
        
        public int ActualizarPaciente(InterfacesMatasanos.ServiceReference1.PacienteEN pModificar) {
            return base.Channel.ActualizarPaciente(pModificar);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pModificar) {
            return base.Channel.ActualizarPacienteAsync(pModificar);
        }
        
        public InterfacesMatasanos.ServiceReference1.PacienteEN[] MostrarPaciente() {
            return base.Channel.MostrarPaciente();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteEN[]> MostrarPacienteAsync() {
            return base.Channel.MostrarPacienteAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.PacienteEN[] BuscarPacientePordni(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente) {
            return base.Channel.BuscarPacientePordni(pPaciente);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteEN[]> BuscarPacientePordniAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente) {
            return base.Channel.BuscarPacientePordniAsync(pPaciente);
        }
        
        public InterfacesMatasanos.ServiceReference1.PacienteEN[] BuscarPacientePorEstado(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente) {
            return base.Channel.BuscarPacientePorEstado(pPaciente);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteEN[]> BuscarPacientePorEstadoAsync(InterfacesMatasanos.ServiceReference1.PacienteEN pPaciente) {
            return base.Channel.BuscarPacientePorEstadoAsync(pPaciente);
        }
        
        public int AgregarCamaAPaciente(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pAgregar) {
            return base.Channel.AgregarCamaAPaciente(pAgregar);
        }
        
        public System.Threading.Tasks.Task<int> AgregarCamaAPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pAgregar) {
            return base.Channel.AgregarCamaAPacienteAsync(pAgregar);
        }
        
        public int ActualizarCamaAPaciente(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pModificar) {
            return base.Channel.ActualizarCamaAPaciente(pModificar);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarCamaAPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pModificar) {
            return base.Channel.ActualizarCamaAPacienteAsync(pModificar);
        }
        
        public int EliminarCamaAPaciente(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pEliminar) {
            return base.Channel.EliminarCamaAPaciente(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> EliminarCamaAPacienteAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pEliminar) {
            return base.Channel.EliminarCamaAPacienteAsync(pEliminar);
        }
        
        public InterfacesMatasanos.ServiceReference1.PacienteCamaEN[] MostrarPacienteCama() {
            return base.Channel.MostrarPacienteCama();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteCamaEN[]> MostrarPacienteCamaAsync() {
            return base.Channel.MostrarPacienteCamaAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.PacienteCamaEN[] BuscraCamaPacientePorFecha(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pPC) {
            return base.Channel.BuscraCamaPacientePorFecha(pPC);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PacienteCamaEN[]> BuscraCamaPacientePorFechaAsync(InterfacesMatasanos.ServiceReference1.PacienteCamaEN pPC) {
            return base.Channel.BuscraCamaPacientePorFechaAsync(pPC);
        }
        
        public int AgregarVisita(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar) {
            return base.Channel.AgregarVisita(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> AgregarVisitaAsync(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar) {
            return base.Channel.AgregarVisitaAsync(pEliminar);
        }
        
        public int EliminarVisita(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar) {
            return base.Channel.EliminarVisita(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> EliminarVisitaAsync(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pEliminar) {
            return base.Channel.EliminarVisitaAsync(pEliminar);
        }
        
        public InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[] MostrarVisita() {
            return base.Channel.MostrarVisita();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[]> MostrarVisitaAsync() {
            return base.Channel.MostrarVisitaAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[] BuscarVisita(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pVisita) {
            return base.Channel.BuscarVisita(pVisita);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.VisitaMedicaEN[]> BuscarVisitaAsync(InterfacesMatasanos.ServiceReference1.VisitaMedicaEN pVisita) {
            return base.Channel.BuscarVisitaAsync(pVisita);
        }
        
        public string AgregarPlanta(InterfacesMatasanos.ServiceReference1.PlantaEN pAgregar) {
            return base.Channel.AgregarPlanta(pAgregar);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPlantaAsync(InterfacesMatasanos.ServiceReference1.PlantaEN pAgregar) {
            return base.Channel.AgregarPlantaAsync(pAgregar);
        }
        
        public int ActualizarPlanta(InterfacesMatasanos.ServiceReference1.PlantaEN pEliminar) {
            return base.Channel.ActualizarPlanta(pEliminar);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarPlantaAsync(InterfacesMatasanos.ServiceReference1.PlantaEN pEliminar) {
            return base.Channel.ActualizarPlantaAsync(pEliminar);
        }
        
        public InterfacesMatasanos.ServiceReference1.PlantaEN[] MostraPlantas() {
            return base.Channel.MostraPlantas();
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PlantaEN[]> MostraPlantasAsync() {
            return base.Channel.MostraPlantasAsync();
        }
        
        public InterfacesMatasanos.ServiceReference1.PlantaEN[] BuscarPlanta(InterfacesMatasanos.ServiceReference1.PlantaEN pPlanta) {
            return base.Channel.BuscarPlanta(pPlanta);
        }
        
        public System.Threading.Tasks.Task<InterfacesMatasanos.ServiceReference1.PlantaEN[]> BuscarPlantaAsync(InterfacesMatasanos.ServiceReference1.PlantaEN pPlanta) {
            return base.Channel.BuscarPlantaAsync(pPlanta);
        }
    }
}
